### ISSUE TITLE
JavaScript interpreter error

### ISSUE THREAD

**Issue by scoliono** [iv-org/inv_sig_helper#48]
This is not a duplicate of #44, I've already applied the fix for that. This just started happening to me this evening, and at the same time I'm now getting random 403s with /videoplayback.

```
inv_sig_helper-1  | [2024-12-19T02:26:24Z ERROR inv_sig_helper_rust::jobs] JavaScript interpreter error (sig code): Some(Exception { message: Some("unexpected token in expression: '}'"), file: Some("eval_script"), line: Some(1), column: Some(215), stack: Some("    at eval_script:1:215\n") })
```

I'm glad to hear we will be getting Invidious Companion soon :sweat_smile:

**Comment by alive4ever** [comment]
Hi, I somehow managed to fix the signature extraction.

First, revert to [this commit ](https://github.com/iv-org/inv_sig_helper/commit/ef11b83a97adfe7c15c92194af8e61d4480e878d), since the last commits changes the algorithm too much.

`git reset ef11b83a && git restore .`

Then apply this fix (i.e. `git apply fixup-inv-sig-helper.patch`)

[fixup-inv-sig-helper.patch](https://github.com/user-attachments/files/18206544/fixup-inv-sig-helper.patch)

Tested with player version `03dbdfad`.

**Comment by GTechAlpha** [comment]
Here's a minimal patch for this in the mean time:

https://0x0.st/XCDZ.patch

**Comment by squatica** [comment]
Hmm, why not a PR?

**Comment by stryk3rr3al** [comment]
+1 for PR and following this issue.
